[build]
  command = "rm -rf node_modules && npm install --force && npm run build"
  publish = "dist"
  NODE_VERSION = "18.20.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NPM_FLAGS = "--force"
