[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max_old_space_size=4096"
  TSC_COMPILE_ON_ERROR = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    "X-Frame-Options" = "DENY"
    "X-XSS-Protection" = "1; mode=block"

[[headers]]
  for = "/*.js"
  [headers.values]
    "Content-Type" = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    "Content-Type" = "text/css"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    "Content-Type" = "application/javascript"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    "Content-Type" = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    "Content-Type" = "application/javascript"

[[headers]]
  for = "/dist/*.js"
  [headers.values]
    "Content-Type" = "text/javascript"

