[build]
  command = "npm cache clean --force && npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  NODE_VERSION = "18.20.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
