[build]
  command = "rm -rf node_modules && npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.20.0"
  NPM_FLAGS = "--legacy-peer-deps --force"
  NODE_OPTIONS = "--max_old_space_size=4096"

