[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max_old_space_size=4096"
  TSC_COMPILE_ON_ERROR = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

