services:
  - type: web
    name: kkmk-backend
    env: node
    buildCommand: |
      npm run install-all
      cd frontend && cp tsconfig.prod.json tsconfig.json && cd ..
      npm run build
    startCommand: cd backend && node server.js
    healthCheckPath: /health
    healthCheckTimeout: 100
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_USER
        fromDatabase:
          name: kkmk
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: kkmk
          property: password
      - key: DB_HOST
        fromDatabase:
          name: kkmk
          property: host
      - key: DB_PORT
        fromDatabase:
          name: kkmk
          property: port
      - key: DB_NAME
        fromDatabase:
          name: kkmk
          property: database
      - key: CORS_ORIGIN
        value: https://kkmkpayatas.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: kkmk
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        value: dvzbgapue
      - key: CLOUDINARY_API_KEY
        value: 539274975653933
      - key: CLOUDINARY_API_SECRET
        value: Lstsyvr-PR9eR9tp1v5pqjysoLI

databases:
  - name: kkmk
    databaseName: kkmk
    user: kkmk_db
    plan: free # Explicitly specify the free plan
    ipAllowList: [] # Allow all IPs
