services:
  - type: web
    name: KMFI
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PROD_DATABASE_URL
        sync: false
      - key: PORT
        value: 5175
      - key: CLOUDINARY_CLOUD_NAME
        value: dvzbgapue
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
